# Generated by Django 6.0.3 on 2026-06-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_is_online'),
        ('account', '0003_socialaccount'),
    ]

    operations = [
    ]
