# Generated by Django 6.0.3 on 2026-06-12 13:52

import django.db.models.deletion
import statemachine.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_timeout', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('evaluated', 'Evaluated')], default='pending', max_length=16)),
                ('answer_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('category', models.CharField(default='any', max_length=100)),
                ('is_ai_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_status', models.CharField(choices=[('lobby', 'Lobby'), ('answering', 'Answering'), ('evaluation', 'Evaluation'), ('nomination', 'Nomination'), ('game_over', 'Game Over')], default='lobby', max_length=32)),
                ('end_reason', models.CharField(blank=True, choices=[('last_player_alive', 'Last player alive'), ('questions_exhausted', 'Questions exhausted'), ('cancelled', 'Cancelled')], max_length=64, null=True)),
                ('question_asked_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('answer_time_limit_ms', models.PositiveIntegerField(default=20000)),
                ('evaluation_time_limit_ms', models.PositiveIntegerField(default=3000)),
                ('nomination_time_limit_ms', models.PositiveIntegerField(default=10000)),
                ('nomination_started_at', models.DateTimeField(blank=True, null=True)),
                ('max_players', models.PositiveIntegerField(default=5)),
                ('current_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.answerattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(statemachine.mixins.MachineMixin, models.Model),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='game.gamesession'),
        ),
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(choices=[('human', 'Human'), ('bot', 'Bot')], default='human', max_length=16)),
                ('display_name', models.CharField(max_length=100)),
                ('seat_number', models.PositiveIntegerField()),
                ('lives', models.PositiveIntegerField(default=3)),
                ('points', models.IntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('total_answer_time_ms', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players', to='game.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_session_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_id', 'seat_number'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_where_current', to='game.sessionplayer'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='host_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to='game.sessionplayer'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_correct_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_where_last_correct', to='game.sessionplayer'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_nominated_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_where_last_nominated', to='game.sessionplayer'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to='game.sessionplayer'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='game.sessionplayer'),
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_questions', to='game.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='game.gamesession')),
            ],
            options={
                'ordering': ['session_id', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.sessionquestion'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='session_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='game.sessionquestion'),
        ),
        migrations.AddConstraint(
            model_name='sessionplayer',
            constraint=models.UniqueConstraint(fields=('session', 'seat_number'), name='unique_seat_number_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('session', 'user'), name='unique_human_user_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order_index'), name='unique_question_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_question_once_per_session'),
        ),
    ]
