# Generated by Django 6.0.3 on 2026-04-17 13:43

import django.db.models.deletion
import statemachine.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(default='Lobby', max_length=50)),
                ('session_questions_ids', models.JSONField(default=list)),
                ('current_player_id', models.IntegerField(blank=True, null=True)),
                ('nominator_id', models.IntegerField(blank=True, null=True)),
                ('current_question_id', models.IntegerField(blank=True, null=True)),
                ('question_asked_count', models.IntegerField(default=0)),
                ('player_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('player_answer_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(statemachine.mixins.MachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lives', models.IntegerField(default=3)),
                ('points', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players', to='game.gamesession')),
            ],
        ),
    ]
