# Generated by Django 6.0.3 on 2026-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_host_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='max_players',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
