# Generated by Django 6.0.3 on 2026-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_current_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='answer_time_limit_ms',
            field=models.PositiveIntegerField(default=20000),
        ),
    ]
