# Generated by Django 6.0.3 on 2026-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='any', max_length=100),
        ),
    ]
