# Generated by Django 6.0.3 on 2026-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_evaluation_time_limit_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
