# Generated by Django 6.0.3 on 2026-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_nomination_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
