# Generated by Django 6.0.3 on 2026-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
