# Generated by Django 6.0.3 on 2026-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_sessionplayer_lives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
