# Generated by Django 6.0.3 on 2026-06-19 07:13

from django.db import migrations, models


def verify_existing_curated_questions(apps, schema_editor):
    # Existing non-AI questions are the curated seed set; keep them assignable
    # by marking them verified. Previously generated AI questions stay
    # unverified and must be approved manually.
    Question = apps.get_model('game', 'Question')
    Question.objects.filter(is_ai_generated=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_sessionplayer_active_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            verify_existing_curated_questions,
            migrations.RunPython.noop,
        ),
    ]
