# Generated by Django 6.0.3 on 2026-06-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_question_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='extra_questions_generated',
            field=models.BooleanField(default=False),
        ),
    ]
